Feat: Multiple tokens form
Ashe-Oro-Accelerator/token-holders-list pull request #17
Opened 2024-03-11 21:24 UTC by StanislawMazowieckiAriane

Fixes #16

2024-03-12 09:18 UTC, michalrozekariane approved these changes

2024-03-12 09:18 UTC, michalrozekariane commented on src/App.tsx
> +          return fetchData(url);
I think you can destructure `tokenId` and `minAmount` here right away

2024-03-12 13:14 UTC, StanislawMazowieckiAriane commented on src/App.tsx
> +          return fetchData(url);
Done

2024-03-13 11:31 UTC, piotrswierzy requested changes

2024-03-13 11:31 UTC, piotrswierzy commented on src/App.tsx
> +  };
Maybe write a unit test for it

2024-03-15 14:56 UTC, StanislawMazowieckiAriane commented
This PR is too outdated regarding https://github.com/Ashe-Oro-Accelerator/token-holders-list/pull/18
It contains several bugs etc which are fixed in the new PR.
Closing

2024-03-15 14:56 UTC, closed without merging

2024-03-15 14:56 UTC, StanislawMazowieckiAriane commented
This PR is too outdated regarding https://github.com/Ashe-Oro-Accelerator/token-holders-list/pull/18
It contains several bugs etc which are fixed in the new PR.
Closing